#!/usr/bin/env python3
# from typing import *

YES = "Yes"
NO = "No"


# def solve(n: int, a: List[int]) -> str:
def solve(n, a):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    s1, s2 = input()
    t1, t2 = input()
    points = "ABCDE"
    if (points[(points.index(s1) + 1) % 5] == s2) or (
        points[(points.index(s1) - 1) % 5] == s2
    ):
        s_class = 1
    else:
        s_class = 2
    if (points[(points.index(t1) + 1) % 5] == t2) or (
        points[(points.index(t1) - 1) % 5] == t2
    ):
        t_class = 1
    else:
        t_class = 2
    print("Yes" if s_class == t_class else "No")


if __name__ == "__main__":
    main()
