#!/usr/bin/env python3
# from typing import *



# def solve(T: int, X: int) -> float:
def solve(T, X):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    T, X = map(int, input().split())
    a = solve(T, X)
    print(a)

if __name__ == '__main__':
    main()
