#!/usr/bin/env python3
# from typing import *

YES = "Yes"
NO = "No"


# def solve(N: int, A: List[int]) -> Tuple[str, str, List[str], str, List[str]]:
def solve(N, A):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys

    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    A = [None for _ in range(N)]
    for i in range(N):
        A[i] = int(next(tokens))
    assert next(tokens, None) is None
    Yes, x, B, y, C = solve(N, A)
    print(Yes)
    print(x, *[B[i] for i in range(x)])
    print(y, *[C[i] for i in range(y)])


if __name__ == "__main__":
    main()
