#!/usr/bin/env python3
# from typing import *



# def solve(A: int, B: int, C: int, D: int, E: int) -> int:
def solve(A, B, C, D, E):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A = int(input())
    B = int(input())
    C = int(input())
    D = int(input())
    E = int(input())
    a = solve(A, B, C, D, E)
    print(a)

if __name__ == '__main__':
    main()
