#!/usr/bin/env python3
# from typing import *


# def solve(N: int, h: List[int]) -> int:
def solve(N: int, h: list[int], K: int):
    result: list[int] = [10**10] * N
    result[0] = 0
    for i in range(1, N):
        for j in range(1, K + 1):
            if i - j < 0:
                break
            result[i] = min(
                result[i],
                result[i - j] + abs(h[i] - h[i - j]),
            )
    return result[-1]


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, K = map(int, input().split())
    h = list(map(int, input().split()))
    a = solve(N, h, K)
    print(a)


if __name__ == "__main__":
    main()
