#!/usr/bin/env python3
# from typing import *
from collections import deque


# def solve(N: int) -> int:
def solve(N):
    """
    0,2,4,6,8,20,22,24,26,28
    を2で割ると、
    0,1,2,3,4,10,11,12,13,14になる。
    N番目の整数を5進数とみなして値を計算するとN−1になる
    """
    d = deque()
    if N == 0:
        return [0]
    N -= 1
    while N != 0:
        d.appendleft(N % 5 * 2)
        N //= 5
    return d


def solve2(N: int):
    # 自分で考えたWAの回答
    # ind = 10 * (N // 5 + 1) + 2 * (N % 5 - 1)
    ind = 2 * ((N - 1) % 5) + 10 * ((N - 1) // 5 + 1)
    return ind


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    # nums = list(range(1, N + 1))
    a = solve(N)
    print(*a, sep="")


if __name__ == "__main__":
    main()
