#!/usr/bin/env python3
# from typing import *
from collections import deque


# def solve(N: int) -> int:
def solve(N):
    """
    0,2,4,6,8,20,22,24,26,28
    を2で割ると、
    0,1,2,3,4,10,11,12,13,14になる。
    N番目の整数を5進数とみなして値を計算するとN−1になる
    """
    d = deque()
    if N == 0:
        return [0]
    N -= 1
    while N != 0:
        d.appendleft(N % 5 * 2)
        N //= 5
    return d


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    a = solve(N)
    print(*a, sep="")


if __name__ == "__main__":
    main()
