#!/usr/bin/env python3
# from typing import *


# def solve(K: int, G: int, M: int) -> Tuple[int, int]:
def solve(K, G, M):
    g = 0
    m = 0
    for _ in range(K):
        if g == G:
            g = 0
        elif m == 0:
            m = M
        else:
            while True:
                if m == 0 or g == G:
                    break
                g += 1
                m -= 1
    return g, m


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    K, G, M = map(int, input().split())
    c, d = solve(K, G, M)
    print(c, d)


if __name__ == "__main__":
    main()
