#!/usr/bin/env python3
# from typing import *


# def solve(N: int, T: int, A: List[int], B: List[int]) -> List[str]:
# def solve(N: int, T: int, A: list[int], B: list[int]):
#     ans_list = [0] * N
#     ans = []
#     for a, b in zip(A, B):
#         ans_list[a - 1] += b
#         print(set(ans_list))


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    """
    setにするのが時間がかかる。
    得点ごとの辞書とか？
    全員分のデータを保持しておく必要がないんだと思う。
    """
    N, T = map(int, input().split())
    ans_list = [0] * N
    # A = [None for _ in range(T)]
    # B = [None for _ in range(T)]
    for i in range(T):
        a, b = map(int, input().split())
        ans_list[a - 1] += b
        print(len(set(ans_list)))
    # solve(N, T, A, B)
    # for i in range(T):
    # print(ans[i])


if __name__ == "__main__":
    main()
