#!/usr/bin/env python3
# from typing import *



# def solve(K: int, X: int, Y: int) -> Tuple[str, List[str], List[str]]:
def solve(K, X, Y):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    K = int(input())
    X, Y = map(int, input().split())
    n, a, b = solve(K, X, Y)
    print(n)
    for i in range(n):
        print(a[i], b[i])

if __name__ == '__main__':
    main()
