#!/usr/bin/env python3
# from typing import *
from math import floor


# def solve(A: int, B: int) -> int:
def solve(A, B):
    """
    floor(price * 0.08) = 100
    floor(price * 0.1) = 100
    x * 0.08 = 100
    """
    ans = -1
    for i in range(1, 1251):
        if (floor(i * 0.08) == A) and (floor(i * 0.1) == B):
            ans = int(i)
            break
    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A, B = map(int, input().split())
    a = solve(A, B)
    print(a)


if __name__ == "__main__":
    main()
