#!/usr/bin/env python3
# from typing import *


# def solve(N: int) -> Any:
def solve(N):
    ans = []
    for i in range(0, N + 1):
        for j in range(0, N - i + 1):
            for k in range(0, N - i - j + 1):
                ans.append([i, j, k])
    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    ans = solve(N)
    for i in ans:
        print(*i)  # TODO: edit here


if __name__ == "__main__":
    main()
