#!/usr/bin/env python3
# from typing import *


# def solve(H: int, W: int, A: int, B: int) -> int:
def solve(H, W, A, B):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    H, W, A, B = map(int, input().split())
    a = solve(H, W, A, B)
    print(a)


if __name__ == "__main__":
    main()
