#!/usr/bin/env python3
# from typing import *


# def solve(A: List[str]) -> Any:
def solve(A):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A = []
    while True:
        try:
            i = input()
            A.append(int(i))
        except EOFError:
            break
    print(*A[::-1], sep="\n")  # TODO: edit here


if __name__ == "__main__":
    main()
