#!/usr/bin/env python3
# from typing import *


# def solve(N: int, h: List[int]) -> int:
def solve(N: int, h: list[int]):
    result: list[int] = [-1] * N
    result[0] = 0
    result[1] = min(result[0], result[0] + abs(h[1] - h[0]))
    for i in range(2, N):
        result[i] = min(
            result[i - 1] + abs(h[i] - h[i - 1]),
            result[i - 2] + abs(h[i] - h[i - 2]),
        )
    return result[-1]


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    h = list(map(int, input().split()))
    a = solve(N, h)
    print(a)


if __name__ == "__main__":
    main()
