#!/usr/bin/env python3
# from typing import *


# def solve(D: int, N: int) -> int:
def solve(D, N):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    D, N = map(int, input().split())
    a = solve(D, N)
    print(a)


if __name__ == "__main__":
    main()
