#!/usr/bin/env python3
# from typing import *


# def solve(A: int, B: int) -> int:
def solve(A, B):
    ans = []
    for i in range(10):
        if (i) != (A + B):
            ans.append(i)
    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A, B = map(int, input().split())
    a = solve(A, B)
    print(a[0])


if __name__ == "__main__":
    main()
