#!/usr/bin/env python3
# from typing import *


# def solve(N: int) -> int:
def solve(N):
    result = 0
    for s in bin(N)[2:][::-1]:
        if s == "0":
            result += 1
        else:
            break
    return result



# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    a = solve(N)
    print(a)


if __name__ == "__main__":
    main()
