#!/usr/bin/env python3
# from typing import *

YES = "Yes"
NO = "No"


# def solve(S: str) -> str:
def solve(S: str):
    if not S[0].isupper():
        return NO
    for i in range(1, len(S)):
        if S[i].isupper():
            return NO
    return YES


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    a = solve(S)
    print(a)


if __name__ == "__main__":
    main()
