#!/usr/bin/env python3
# from typing import *
import math
from collections import Counter


# def solve(S: str) -> int:
def solve(S):
    """
    1. 全探索
      2 <= S <= 10^6だから10^6*(10^6 - 1)/(2)で間に合わない
    同じ文字が含まれていたら元の文字列を作れるので+1する
    """
    N = len(S)
    ans = math.comb(N, 2)
    # print(f"{ans=}")
    counter = dict(Counter(S))
    if len(counter) == 1:
        return 1
    for letter, letter_count in counter.items():
        if letter_count > 1:
            ans -= math.comb(letter_count, 2)
    if any(x > 1 for x in counter.values()):
        ans += 1
    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    a = solve(S)
    print(a)


if __name__ == "__main__":
    main()
