#!/usr/bin/env python3
# from typing import *

YES = "Yes"
NO = "No"


# def solve(N: int, H: int, W: int, A: List[int], B: List[int]) -> str:
def solve(N, H, W, A, B):
    ans = NO
    h = 0
    w = 0
    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, H, W = map(int, input().split())
    A = [None for _ in range(N)]
    B = [None for _ in range(N)]
    for i in range(N):
        A[i], B[i] = map(int, input().split())
    a = solve(N, H, W, A, B)
    print(a)


if __name__ == "__main__":
    main()
