#!/usr/bin/env python3
# from typing import *

"""
input:
6
4 1 -1 5 3 2

output:
3 5 4 1 2 6
"""


# def solve(N: int, A: List[int]) -> List[str]:
def solve(N: int, A: list[int]):
    "linked listをつくってprintする？"
    d = dict()
    for ind, num in enumerate(A):
        d[num] = ind + 1
    res: list[int] = [d[-1]]
    # inv_d: dict[int, int] = dict(d.values(), d.keys())
    for i in range(N - 1):
        res.append(d[res[-1]])
    return res


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    A = list(map(int, input().split()))
    print(*solve(N, A))


if __name__ == "__main__":
    main()
