#!/usr/bin/env python3
# from typing import *


# def solve(N: int, A: int, B: int) -> int:
def solve(N, A, B):
    """
    16, 3, 4
    7       7       7
    bbbaaaa bbbaaaa bbbaaaa
    16//7 = 2
    16%7 = 2
    """
    ans = (N // (A + B)) * A
    if (N % (A + B)) > A:
        ans += A
    else:
        ans += N % (A + B)
    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, A, B = map(int, input().split())
    a = solve(N, A, B)
    print(a)


if __name__ == "__main__":
    main()
