#!/usr/bin/env python3
# from typing import *
import numpy as np


# def solve(N: int, A: List[int]) -> int:
def solve(A, mid):
    pass


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    _ = int(input())
    A = list(map(int, input().split()))
    cumsum_A = np.cumsum(A)
    candidate = -np.min(cumsum_A)
    if all(cumsum_A >= 0):
        print(cumsum_A[-1])
    else:
        print((candidate + cumsum_A)[-1])


if __name__ == "__main__":
    main()
