#!/usr/bin/env python3
# from typing import *


# def solve(b: str) -> str:
def solve(b):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    b = input()
    a = solve(b)
    print(a)


if __name__ == "__main__":
    main()
