#!/usr/bin/env python3
# from typing import *


# def solve(N: int, S: int, M: int, L: int) -> int:
def solve(N, S, M, L):
    """
    ありえる全部の組み合わせを考える。
    全部6個いりのSパックだと、100//6 + 1
    """
    ans = 10**10
    for i in range(N // 6 + 2):
        for j in range(N // 8 + 2):
            for k in range(N // 12 + 2):
                if (6 * i + 8 * j + 12 * k) >= N:
                    ans = min(ans, S * i + M * j + L * k)
    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, S, M, L = map(int, input().split())
    a = solve(N, S, M, L)
    print(a)


if __name__ == "__main__":
    main()
