#!/usr/bin/env python3
# from typing import *
import re

YES = "Yes"
NO = "No"


# def solve(S: str) -> str:
def solve(S):
    return YES if re.fullmatch(r"A*B*C*", S) else NO


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    a = solve(S)
    print(a)


if __name__ == "__main__":
    main()
